WIP debugging fishy p-value distribution
In the process of trying to fix the wrong polarity of the p-threshold
application we might have introduced bugs in the statistical procedure.

P-value Statistics:
Range: 0.00e+00 to 1.00e+00
Mean: 8.43e-01
Median: 1.00e+00

Cluster Identification Debug:
Number of significant pixels: 1481
Background ROI significant pixels: 1
...
==================================== short test summary info =====================================
FAILED btx/processing/tests/functional/test_multi_peak_masks.py::test_multi_peak_mask_generation -
 TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safe
ly coerced to any supported types according to the casting rule ''safe''
================================= 1 failed, 4 warnings in 2.94s ==================================
(py310_3) ollie@ollie:~/Documents/btx $